# Generated by Django 6.0 on 2026-05-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("view_user_personal_data", "Can view user personal data"),
                    ("change_user_personal_data", "Can change user personal data"),
                ]
            },
        ),
    ]
