x-db-environment: &db-environment
  POSTGRES_DB: pdfactory
  POSTGRES_USER: pdfactory
  POSTGRES_PASSWORD: pdfactory

x-app-environment: &app-environment
  SETTINGS_FILES_FOR_DYNACONF: /etc/pdfactory/settings.yml
  ENVIRONMENTS_FOR_DYNACONF: "false"

services:
  dev:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile

    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspaces:cached
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

  postgres:
    environment:
      <<: *db-environment

  django:
    build:
      args:
        ENVIRONMENT: development
    command: python -Xfrozen_modules=off -m debugpy --listen django:5678 manage.py runserver django:8080 --skip-checks
    environment:
      <<:
        - *app-environment
    volumes:
      - ./src:/usr/src/app:cached
      - ./.devcontainer/settings.yml:/etc/pdfactory/settings.yml:ro

  dramatiq:
    build:
      args:
        ENVIRONMENT: development
    command: python -Xfrozen_modules=off -m debugpy --listen dramatiq:5678 manage.py rundramatiq --skip-checks --watch .
    environment:
      <<:
        - *app-environment
    volumes:
      - ./src:/usr/src/app:cached
      - ./.devcontainer/settings.yml:/etc/pdfactory/settings.yml:ro
