"""
Django settings for pdfactory project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from importlib import import_module
from pathlib import Path

from main.utils import gettext_lazy as _
from main.utils import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-2#qhiwqw7j+a%#bd16@m0(%od6(&sx0fz18ht77$icu+zys5xh"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django_dramatiq",
    "unfold",
    "unfold.contrib.forms",
    "unfold.contrib.filters",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "unfold.contrib.import_export",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "guardian",
    "simple_history",
    "import_export",
    "shared.apps.SharedConfig",
    "user.apps.UserConfig",
    "file.apps.FileConfig",
    "cert.apps.CertConfig",
    "course.apps.CourseConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main.wsgi.application"


# region Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# endregion Database


# region Security

# https://docs.djangoproject.com/en/6.0/topics/auth/customizing/#substituting-a-custom-user-model
AUTH_USER_MODEL = "user.User"

# https://django-guardian.readthedocs.io/en/stable/configuration/
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
)

# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# endregion Security


# region Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# endregion Internationalization


# region Static and media files
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# endregion Static and media files


# region Unfold

UNFOLD = {
    "SITE_TITLE": "PDFactory",
    "SITE_HEADER": "PDFactory",
    "SITE_URL": "/",
    "SITE_SYMBOL": "docs",
    "SITE_DROPDOWN": [
        {
            "icon": "commit",
            "title": _("Source code"),
            "link": "https://github.com/Art1xFX/PDFactory",
            "attrs": {
                "target": "_blank",
            },
        },
    ],
    "SIDEBAR": {
        "show_search": True,
        "command_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Courses"),
                "separator": True,
                "items": [
                    {
                        "icon": "school",
                        "title": _("Courses"),
                        "link": reverse_lazy("admin:course_course_changelist"),
                        "permission": lambda request: request.user.has_perm("course.view_course"),
                    },
                    {
                        "icon": "event",
                        "title": _("Intakes"),
                        "link": reverse_lazy("admin:course_intake_changelist"),
                        "permission": lambda request: request.user.has_perm("course.view_intake"),
                    },
                    {
                        "icon": "workspace_premium",
                        "title": _("Certificates"),
                        "link": reverse_lazy("admin:course_certificate_changelist"),
                        "permission": lambda request: request.user.has_perm("course.view_certificate"),
                    },
                    {
                        "icon": "integration_instructions",
                        "title": _("Templates"),
                        "link": reverse_lazy("admin:cert_template_changelist"),
                        "permission": lambda request: request.user.has_perm("cert.view_template"),
                    },
                ],
            },
            {
                "title": _("Files"),
                "separator": True,
                "items": [
                    {
                        "icon": "attach_file",
                        "title": _("Files"),
                        "link": reverse_lazy("admin:file_file_changelist"),
                        "permission": lambda request: request.user.has_perm("file.view_file"),
                    },
                    {
                        "icon": "match_case",
                        "title": _("Fonts"),
                        "link": reverse_lazy("admin:file_fontfamily_changelist"),
                        "permission": lambda request: request.user.has_perm("file.view_fontfamily"),
                    },
                ],
            },
            {
                "title": _("Users and groups"),
                "separator": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "account_circle",
                        "link": reverse_lazy("admin:user_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}


# endregion Unfold


# region Dynaconf settings
# Read more at https://www.dynaconf.com/django/

dynaconf = import_module("dynaconf")

settings = dynaconf.DjangoDynaconf(__name__, ENVVAR_PREFIX_FOR_DYNACONF="PDFACTORY")

# endregion Dynaconf settings
